export const GET_TASKS_SUCCESS = "GET_TASKS";
export const GET_TASKS_LOADING = "GET_TASKS_LOADING";
export const GET_TASKS_ERROR = "GET_TASKS_ERROR";
export const ADD_TASK_SUCESSFULLY = "ADD_TASK";
export const ADD_TASK_LOADING_TASK = "ADD_LOADING_TASK";
export const ADD_TASK_ERROR = "ADD_TASK_ERROR";
