export const GET_USER_DATA = "GET_USER_DATA";
export const GET_USER_DATA_LOADING = "GET_USER_DATA_LOADING";
export const GET_USER_DATA_FAILURE = "GET_USER_DATA_FAILURE";
export const ADD_USER_DATA = "ADD_USER_DATA";
export const ADD_USER_DATA_LOADING = "ADD_USER_DATA_LOADING";
export const ADD_USER_DATA_FAILURE = "ADD_USER_DATA_FAILURE";
